# https://github.com/prettier/prettier/issues/4102
# https://github.com/prettier/prettier/pull/7466
singleQuote: true
tabWidth: 2
trailingComma: all
#trailingComma: es5
overrides:
  - files: '*.ts'
    options:
      tabWidth: 4
      # https://prettier.io/docs/en/options.html#arrow-function-parentheses
      arrowParens: avoid
      # https://prettier.io/docs/en/options.html#parser
      #parser: babel-ts
  - files: '*.js'
    options:
      tabWidth: 4
