@startuml Komponenten

skinparam componentStyle uml2

left to right direction

actor RESTClient

node "Funktionen mit Express" {
  boundary Router
  [Handler Functions]
}

node "Klassen / objektorientiert" {
  [AutoHandler]
  [AutoFileHandler]

  [AutoService]
  [AutoFileService]
}

[sendMail()] as sendMail

entity AutoModel

cloud {
    [Mongoose]
}

cloud {
    [MongDB\nNative Driver]
}

cloud {
    [nodemailer]
}

database "acme (MongoDB)" {
    [Collection Auto]
    [GridFS]
}

node {
    [Mailserver]
}


RESTClient ~~> [Router]
[Router] ..> [Handler Functions]
[Handler Functions] ..> [AutoHandler]
[Handler Functions] ..> [AutoFileHandler]

[AutoHandler] --> [AutoService]
[AutoFileHandler] --> [AutoFileService]
[AutoService] ..> [AutoModel]
[AutoFileService] ..> [AutoModel]

[AutoModel] ~~> [Mongoose]
[AutoFileService] ~~> [MongDB\nNative Driver]
[sendMail] ~~> [nodemailer]
[Mongoose] ~~> [Collection Auto]
[MongDB\nNative Driver] ~~> [GridFS]

[AutoService] --> [sendMail]
[nodemailer] ~~> [Mailserver]

footer (c) Jürgen Zimmermann

@enduml
